namespace CalibraHub.Application.Contracts;

public sealed record ContactDto(
    int Id,
    byte AccountType,
    string AccountCode,
    string AccountTitle,
    string? TaxNumber,
    string? IdentityNumber,
    string? TaxOffice,
    string? Phone,
    string? Email,
    string? Address,
    string? City,
    string? District,
    bool IsActive,
    int? PriceGroupId,
    DateTime CreatedAt,
    string? CountryCode = null,
    string? Mobile = null,
    string? Website = null,
    string? PostalCode = null,
    string? ContactPerson = null,
    string? Neighborhood = null,
    int? SalesRepresentativeId = null);

public sealed record SaveContactRequest(
    int? Id,
    byte AccountType,
    string AccountCode,
    string AccountTitle,
    string? TaxNumber,
    string? IdentityNumber,
    string? TaxOffice,
    string? Phone,
    string? Email,
    string? Address,
    string? City,
    string? District,
    bool IsActive,
    int? PriceGroupId,
    string? CountryCode = null,
    string? Mobile = null,
    string? Website = null,
    string? PostalCode = null,
    string? ContactPerson = null,
    string? Neighborhood = null,
    int? SalesRepresentativeId = null);

public sealed record DeleteContactBody(int Id);
